# Generated by Django 4.1.7 on 2023-03-31 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_libro', models.CharField(max_length=50)),
                ('genero_libro', models.CharField(choices=[('riqueza', 'Riqueza'), ('desarrollo_personal', 'Desarrollo Personal'), ('liderazgo', 'Liderazgo'), ('emprendimiento', 'Emprendimiento'), ('habitos', 'Habitos'), ('analisis_tecnico', 'Analisis Tecnico & Trading')], default='desarrollo_personal', max_length=30)),
                ('autor_libro', models.CharField(max_length=30)),
                ('editorial_libro', models.CharField(max_length=30)),
                ('imagen_libro', models.ImageField(blank=True, null=True, upload_to='libros_publicaciones')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('telefono_contacto', models.IntegerField()),
                ('emai_contacto', models.EmailField(max_length=254)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['vendedor', '-fecha_publicacion'],
            },
        ),
    ]
