# Generated by Django 4.1.7 on 2023-03-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='emai_contacto',
            new_name='email_contacto',
        ),
    ]
