# Generated by Django 4.1.7 on 2023-03-31 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_publicaciones', '0002_rename_emai_contacto_publicacion_email_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha_mensaje', models.DateTimeField(auto_now_add=True)),
                ('publicacion_mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='gestion_publicaciones.publicacion')),
            ],
            options={
                'ordering': ['-fecha_mensaje'],
            },
        ),
    ]
