# Generated by Django 4.1.7 on 2023-04-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_publicaciones', '0003_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='nombre',
        ),
    ]
