# Generated by Django 4.1.7 on 2023-04-06 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_publicaciones', '0005_alter_publicacion_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='publicacion_mensaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='gestion_publicaciones.publicacion'),
        ),
    ]
